name: CloudHub Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest
    env:
      CONNECTEDAPP_CLIENT_ID: ${{ secrets.CONNECTEDAPP_CLIENT_ID }}
      CONNECTEDAPP_CLIENT_SECRET: ${{ secrets.CONNECTEDAPP_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v3
    - name: Build And Deploy to CloudHUb with Maven
      run: mvn clean deploy -DmuleDeploy
